# Generated by Django 2.1.4 on 2018-12-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyTask',
            fields=[
                ('pid', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=60)),
                ('file_name', models.CharField(max_length=60)),
            ],
        ),
    ]
